version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14      
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub     
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: kneerati12345/selenium-docker-test
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - D:\SeleniumProjects\selenium-docker-master\output\Search:/usr/share/udemy/test-output
  book-flight:
    image: kneerati12345/selenium-docker-test
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book-flight-module.xml
    volumes:
      - D:\SeleniumProjects\selenium-docker-master\output\BookFlight:/usr/share/udemy/test-output